### ISSUE TITLE
ArrayIndexOutOfBoundsException when running getMean on ConcurrentDoubleHistogram

### ISSUE THREAD

**Issue by stepanv** [HdrHistogram/HdrHistogram#117]
We experience an intermittent `ArrayIndexOutOfBoundsException` when running `DoubleHistogram.getMean()` of *HdrHistogram* version 2.1.9:
```
java.lang.ArrayIndexOutOfBoundsException
	at org.HdrHistogram.AbstractHistogramIterator.next(AbstractHistogramIterator.java:103)
	at org.HdrHistogram.RecordedValuesIterator.next(RecordedValuesIterator.java:18)
	at org.HdrHistogram.AbstractHistogram.getMean(AbstractHistogram.java:1240)
	at org.HdrHistogram.DoubleHistogram.getMean(DoubleHistogram.java:1036)
	at hdr.histogram.reproducer.HdrHistogramReproducer.lambda$execute$4(HdrHistogramReproducer.java:130)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

In order to reproduce this issue, for a given `ConcurrentDoubleHistogram` instance, we
1. Record a value by running `ConcurrentDoubleHistogram.recordValue()` from multiple threads in parallel
2. And then we read the *mean* (by using an explicit exclusive access) by running `ConcurrentDoubleHistogram.getMean()`

It's quite hard to reproduce the problem which is why I created a reproducer: https://gist.github.com/stepanv/df3b5b913f718d16beef171ad2445d56

To reproduce the issue on my 2 i7 Core Macbook Pro (running MacOS), I need to run:
```
% java -Xmx12g -cp /Users/stepan/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.9/HdrHistogram-2.1.9.jar:. -Dthreads=900 hdr.histogram.reproducer.HdrHistogramReproducer
Jan 17, 2017 1:59:55 PM hdr.histogram.reproducer.HdrHistogramReproducer main
INFO: Starting the RACE!
Jan 17, 2017 1:59:55 PM hdr.histogram.reproducer.HdrHistogramReproducer main
INFO: Parameters:
Jan 17, 2017 1:59:55 PM hdr.histogram.reproducer.HdrHistogramReproducer property
INFO: Parameter 'threads: 900
Jan 17, 2017 1:59:55 PM hdr.histogram.reproducer.HdrHistogramReproducer property
INFO: Parameter 'sleep: 20
Jan 17, 2017 1:59:55 PM hdr.histogram.reproducer.HdrHistogramReproducer property
INFO: Parameter 'request.period: 200
Jan 17, 2017 1:59:55 PM hdr.histogram.reproducer.HdrHistogramReproducer execute
INFO: Load threads started.
Iteration 4900: Recorded 13313 values thanks to 900 load threads in last 251 ms (total stats: 52927761 records in 980 seconds). Mean: 32.512018Jan 17, 2017 2:16:16 PM hdr.histogram.reproducer.HdrHistogramReproducer lambda$execute$4
SEVERE: Exception occurred during metrics consumption!
java.lang.ArrayIndexOutOfBoundsException
        at org.HdrHistogram.AbstractHistogramIterator.next(AbstractHistogramIterator.java:103)
        at org.HdrHistogram.RecordedValuesIterator.next(RecordedValuesIterator.java:18)
        at org.HdrHistogram.AbstractHistogram.getMean(AbstractHistogram.java:1240)
        at org.HdrHistogram.DoubleHistogram.getMean(DoubleHistogram.java:1036)
        at hdr.histogram.reproducer.HdrHistogramReproducer.lambda$execute$4(HdrHistogramReproducer.java:131)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
and I happen to reproduce the problem after 980 seconds while using 900 threads to concurrently record values in the histogram. It was a 4900th `ConcurrentDoubleHistogram` instance that became *inconsistent* and `getMean()` threw an exception.

However, when I run the same test on a powerful server with 72 Xeon cores and 512 GB RAM (running Linux 4.1 kernel), I reproduce the problem always within first 10 seconds of the test. I just run 15000 concurrent threads that update the histogram which results in hundred thousands of updates per second:
```
[root@service tmp]# java -Xmx200g -cp HdrHistogram-2.1.9.jar:. -Dthreads=15000 -Dsleep=30 hdr.histogram.reproducer.HdrHistogramReproducer
Jan 17, 2017 2:43:43 PM hdr.histogram.reproducer.HdrHistogramReproducer main
INFO: Starting the RACE!
Jan 17, 2017 2:43:43 PM hdr.histogram.reproducer.HdrHistogramReproducer main
INFO: Parameters:
Jan 17, 2017 2:43:43 PM hdr.histogram.reproducer.HdrHistogramReproducer property
INFO: Parameter 'threads: 15000
Jan 17, 2017 2:43:43 PM hdr.histogram.reproducer.HdrHistogramReproducer property
INFO: Parameter 'sleep: 30
Jan 17, 2017 2:43:43 PM hdr.histogram.reproducer.HdrHistogramReproducer property
INFO: Parameter 'request.period: 200
Jan 17, 2017 2:43:43 PM hdr.histogram.reproducer.HdrHistogramReproducer execute
INFO: Load threads started.
Iteration 21: Recorded 9505 values thanks to 15000 load threads in last 11 ms (total stats: 1614883 records in 6 seconds). Mean: 32.186503Jan 17, 2017 2:43:49 PM hdr.histogram.reproducer.HdrHistogramReproducer lambda$execute$4
SEVERE: Exception occurred during metrics consumption!
java.lang.ArrayIndexOutOfBoundsException
	at org.HdrHistogram.AbstractHistogramIterator.next(AbstractHistogramIterator.java:103)
	at org.HdrHistogram.RecordedValuesIterator.next(RecordedValuesIterator.java:18)
	at org.HdrHistogram.AbstractHistogram.getMean(AbstractHistogram.java:1240)
	at org.HdrHistogram.DoubleHistogram.getMean(DoubleHistogram.java:1036)
	at hdr.histogram.reproducer.HdrHistogramReproducer.lambda$execute$4(HdrHistogramReproducer.java:127)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Exiting ...
```

Just for the completeness sake, the histogram instance that malfunctions like this is not empty. It becomes somehow inconsistent during the concurrent updates. 
In order to save the state of the malfunctioning histogram, I even tried to serialize (and de-serialize) the histogram instance but unfortunately the de-serialization results in a NPE (looks like another bug in the histogram). I also used the `encodeIntoCompressedByteBuffer()` and `decodeFromCompressedByteBuffer()` methods; however, the decoded histogram worked fine (which is actually a workaround that fixes a malfunctioning histogram).

This problem is described even at Histrix issue tracker: https://github.com/Netflix/Hystrix/issues/788
Their solution was to record the values in a single thread (which we might use as well) but I guess it would be better to make `ConcurrentDoubleHistogram` thread safe.

**Comment by giltene** [comment]
There appears to be a concurrency bug (a race) in the the way shifts are done for ConcurrentDoubleHistogram, which I suspect as a possible root cause. I need to take a hard look at that logic to see how we can safely perform those shifts concurrently, or alternatively (yuck!) make such shifting non-concurrent (shifting is a rare operation) which would result in ConcurrentDoubleHistogram becoming only "mostly concurrent" for value recording (potentially rarely blocking).

**Comment by giltene** [comment]
Note that the Hytrix issue referred is not about this. It was a misuse of non-thread safe (and non-cocurrent) histograms. The issue here (I suspect) is localized to ConcurrentDoubleHistogram. It does not seem to reproduce (so far) on ConcurrentHistogram. Which is why I suspect the race bug that exists in the auto-ranging logic used in DoubleHistogram when that logic is exposed to concurrent modifications.

**Comment by giltene** [comment]
Ok. I think we now have the ConcurrentDoubleHistogram race fixed. It was occurring when auto-ranging "down" to a lower-than-previously-seen value, and the values shift would (concurrently) occur before the double-to-integer (d2i) conversion ratio was updated, and while value recordings could concurrently occur (which would be using a stale d2i ratio. Change https://github.com/HdrHistogram/HdrHistogram/commit/cb59fd8e61c05e25cad83c7b727c941a8273d4d1 fixes the issue, and appears to no longer reproduce with the reproducer supplied above.
Please kick this around (build from master) and test on the machines that you were able to reproduce on before to verify before I close...

**Comment by stepanv** [comment]
Thanks Gil for looking at this. I'm sorry to say it, but the master branch with the cb59fd8 change doesn't fix the problem entirely. I'm unable to reproduce the problem on my mac; but unfortunately, it still occurs on the Linux 4.1 based 72 Xeon cores machine, although it's way rarer than it used to be.

The change seems to be a significant improvement in terms of thread-safety. I know how hard it is to fix races just by looking at the code. So I'm thankful even for that!
Stepan

**Comment by giltene** [comment]
Rarely reproducing races are actually worse than more frequently reproducing ones ;-(
There was probably more than one race, and with the more common one (find by inspection) plugged up by the fix. I'll kick this around on a larger machine and look for the next race.

**Comment by chapj2001** [comment]
I had a similar issue with ConcurrentHistogram. I started out using Histogram concurrently, which of course was wrong. But switching to ConcurrentHistogram still failed for ArrayIndexOutOfBoundsException. My solution was to simply synchronize my access to Histogram. This eliminated my ArrayIndexOutOfBoundsException failures and was faster than ConcurrentHistogram.

Below is a set of junit tests that reliably replicate the problem and my solution. Both testHistogram and testConcurrentHistogram log lots of exceptions but testHistogramManuallySynchronized finishes cleanly without exceptions.
```
import org.HdrHistogram.ConcurrentHistogram;
import org.HdrHistogram.Histogram;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.*;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;

public class HistogramTest {
    private static final Logger LOG = LoggerFactory.getLogger(HistogramTest.class);

    protected class RecordValueRunnable implements Runnable {
        Histogram histogram;
        long value;
        boolean manuallySynchronize = false;

        public RecordValueRunnable(Histogram histogram, long value, boolean manuallySynchronize){
            this.histogram = histogram;
            this.value = value;
            this.manuallySynchronize = manuallySynchronize;
        }

        @Override
        public void run() {
            if(manuallySynchronize){
                synchronized (histogram) {
                    histogram.recordValue(value);
                }
            } else {
                histogram.recordValue(value);
            }
        }
    }

    protected class GetMeanRunnable implements Runnable {
        Histogram histogram;
        boolean manuallySynchronize = false;

        public GetMeanRunnable(Histogram histogram, boolean manuallySynchronize){
            this.histogram = histogram;
            this.manuallySynchronize = manuallySynchronize;
        }

        @Override
        public void run() {
            if(manuallySynchronize){
                synchronized (histogram) {
                    histogram.getMean();
                }
            } else {
                histogram.getMean();
            }
        }
    }

    @Test
    public void testHistogram(){
        run(new Histogram(1), false);
    }

    @Test
    public void testConcurrentHistogram(){
        run(new ConcurrentHistogram(1), false);
    }

    @Test
    public void testHistogramManuallySynchronized(){
        run(new Histogram(1), true);
    }

    private void run(Histogram histogram, boolean manuallySynchronize) {
        ExecutorService executorService = Executors.newFixedThreadPool(16);
        long value = 0;
        List<Runnable> testRunnableList = new ArrayList<>();
        long numRuns = 25000;
        for(int i=0; i<numRuns; i++){
            value = value + i;
            testRunnableList.add(new RecordValueRunnable(histogram, value, manuallySynchronize));
            testRunnableList.add(new GetMeanRunnable(histogram, manuallySynchronize));
            testRunnableList.add(new RecordValueRunnable(histogram, value+1, manuallySynchronize));
            testRunnableList.add(new GetMeanRunnable(histogram, manuallySynchronize));
            testRunnableList.add(new RecordValueRunnable(histogram, value+2, manuallySynchronize));
            testRunnableList.add(new GetMeanRunnable(histogram, manuallySynchronize));
            testRunnableList.add(new RecordValueRunnable(histogram, value+3, manuallySynchronize));
            testRunnableList.add(new GetMeanRunnable(histogram, manuallySynchronize));
            testRunnableList.add(new RecordValueRunnable(histogram, value+4, manuallySynchronize));
            testRunnableList.add(new GetMeanRunnable(histogram, manuallySynchronize));
            testRunnableList.add(new RecordValueRunnable(histogram, value+5, manuallySynchronize));
            testRunnableList.add(new GetMeanRunnable(histogram, manuallySynchronize));
            testRunnableList.add(new RecordValueRunnable(histogram, value, manuallySynchronize));
        }
        Collection<Future<?>> futures = new ArrayList<>();
        long start = System.nanoTime();
        for(Runnable runnable: testRunnableList){
            futures.add(executorService.submit(runnable));
        }
        long arrayIndexOutOfBoundsExceptionCount = 0;
        long concurrentModificationExceptionCount = 0;
        long exceptionCount = 0;
        for(Future future: futures){
            try {
                future.get();
            } catch (Exception e) {
                Throwable cause = e.getCause();
                if(e.getCause() instanceof ArrayIndexOutOfBoundsException){
                    arrayIndexOutOfBoundsExceptionCount++;
                } else if(e.getCause() instanceof ConcurrentModificationException){
                    concurrentModificationExceptionCount++;
                } else {
                    exceptionCount++;
                }
            }
        }
        long elapsed = System.nanoTime() - start;
        float elapsedSeconds = ((float)elapsed)/1000f/1000f/1000f;
        LOG.info("Elapsed={}s({}us/run), indexOutOfBounds={}, concurrentMod={}, others={}",
                elapsedSeconds,
                ((float)elapsed)/1000f/numRuns,
                arrayIndexOutOfBoundsExceptionCount,
                concurrentModificationExceptionCount,
                exceptionCount);
    }
}
```

**Comment by giltene** [comment]
@stepanv : It appears that your reproducer is also doing the getMean() calls concurrently with modifications. This use case (queries concurrent with modifications) is not supported according to the ConcurrentDoubleHistogram JavaDoc. This is what ConcurrentRecorder is meant for: safe concurrent modification, clean "sampling" of a stable histogram snapshot, and queries performed on the stable sample.

**Comment by giltene** [comment]
Any news on whether this still reproduces?

I had recently fixed another concurrent race in ConcurrentDoubleHistogram as part of addressing
https://github.com/HdrHistogram/HdrHistogram/issues/156 . not yet pushed to maven central, but buolding from master on github has fixed version.
