### ISSUE TITLE
IndexOutOfBoundsException in ConcurrentHistogram

### ISSUE THREAD

**Issue by igouss** [HdrHistogram/HdrHistogram#151]
I'm not sure if this is dup of 46, 87, 117 but I saw this in the logs for HdrHistogram version 2.1.10

```
java.lang.IndexOutOfBoundsException: index 31744
    at java.util.concurrent.atomic.AtomicLongArray.checkedByteOffset(Unknown Source)
    at java.util.concurrent.atomic.AtomicLongArray.lazySet(Unknown Source)
    at org.HdrHistogram.ConcurrentHistogram.clearCounts(ConcurrentHistogram.java:443)
    at org.HdrHistogram.DoubleHistogram.reset(DoubleHistogram.java:577)
    at org.HdrHistogram.DoubleRecorder.performIntervalSample(DoubleRecorder.java:206)
    at org.HdrHistogram.DoubleRecorder.reset(DoubleRecorder.java:193)
    at io.micrometer.core.instrument.distribution.TimeWindowPercentileHistogram.resetBucket(TimeWindowPercentileHistogram.java:59)
    at io.micrometer.core.instrument.distribution.TimeWindowPercentileHistogram.resetBucket(TimeWindowPercentileHistogram.java:31)
    at io.micrometer.core.instrument.distribution.AbstractTimeWindowHistogram.rotate(AbstractTimeWindowHistogram.java:255)
    at io.micrometer.core.instrument.distribution.AbstractTimeWindowHistogram.takeSnapshot(AbstractTimeWindowHistogram.java:157)
    at io.micrometer.core.instrument.AbstractTimer.takeSnapshot(AbstractTimer.java:188)
    at io.micrometer.prometheus.PrometheusTimer.takeSnapshot(PrometheusTimer.java:99)
```

**Comment by giltene** [comment]
Been looking for ways for this to occur. It basically requires the array lengths of inactiveCounts array manipulated at https://github.com/HdrHistogram/HdrHistogram/blob/HdrHistogram-2.1.10/src/main/java/org/HdrHistogram/ConcurrentHistogram.java#L443 to be different from that of the activeCounts array. And this code is protected by the same ReentrantLock that protects all changes to array lengths, and the changes always change together (e.g. in resize()).

Do you see this often enough to be able to reproduce, or perhaps to try out a diagnostics version to get more info when it happens?

**Comment by igouss** [comment]
We do see OOM exceptions on some data sets so its quite possible that they are related.
I can try to run a diagnostics version if you have one.

**Comment by giltene** [comment]
Ah, the possibility that this is OOM-related makes me feel better. I’ve fixed an easy cause for that with 
https://github.com/HdrHistogram/HdrHistogram/commit/1beb18b80ff5b84b87817ca0a2a4d1884254c969 (Making resize allocate all-or-nothing such that even an OOM will not result in mismatched lengths). Running with a build of the latest github master may eliminate the above exceptions if they were only occurring after OOM situations. And if you currently see those exceptions frequently enough that not seeing them anymore is an indication of a likely fix, that would be useful information.

I’m considering adding more detailed and verbose exception throwing in place of current asserts, for improved field-runtime diagnostics purposes. It is probably harmless in the non-fastpath-recording code, and will help provide richer diagnostics if concurrency race exceptions like this do occur due to potentially not-yet-found bugs.

**Comment by igouss** [comment]
Once we resolved OOM errors this problem got resolved too.
