### ISSUE TITLE
hdrhistogram measurement type with YCSB gives error with java 11 java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter Error

### ISSUE THREAD

**Issue by ayamResearch** [HdrHistogram/HdrHistogram#175]
I have been using YCSB 0.17.0 with mongodb and use measurement type = hdrhistogram. Initially I had java 8 installed on the system. When I upgraded it to Java 11. ycsb run command started giving error:

Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
at org.HdrHistogram.HistogramLogWriter.outputIntervalHistogram(HistogramLogWriter.java:105)
at org.HdrHistogram.HistogramLogWriter.outputIntervalHistogram(HistogramLogWriter.java:127)
at org.HdrHistogram.HistogramLogWriter.outputIntervalHistogram(HistogramLogWriter.java:147)
at site.ycsb.measurements.OneMeasurementHdrHistogram.exportMeasurements(OneMeasurementHdrHistogram.java:112)
at site.ycsb.measurements.Measurements.exportMeasurements(Measurements.java:260)
at site.ycsb.Client.exportMeasurements(Client.java:268)
at site.ycsb.Client.main(Client.java:392)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
... 7 more

To solve this issue, I added dependency in the hdrhistogram pom.xml file as follows.

javax.xml.bind
jaxb-api
2.3.0

org.glassfish.jaxb
jaxb-runtime
2.3.0
mvn install works on hdrhistogram but ycsb run still complains about not having the lib javax.
mvn version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/pkb/maven
Java version: 11.0.9.1, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-1029-aws", arch: "amd64", family: "unix"

Please let me know what I am missing here

**Comment by giltene** [comment]
The issue here seems to be that YCSB 0.17.0 uses a n old version of HdrHistogram (version 2.1.4 from 2015) which predated Java 9 and the deprecation (and eventual removal in 11) of jaxb from the JDK. Later versions of HdrHistogram (2.1.10 and above) are built to run across Java 7...16 with no external dependencies. See https://github.com/HdrHistogram/HdrHistogram/issues/125 for details.

A PR to YCSB to use a later version of HdrHistogram would probably be a good thing...
