### ISSUE TITLE
java.lang.IndexOutOfBoundsException on Java 8

### ISSUE THREAD

**Issue by ygree** [HdrHistogram/HdrHistogram#179]
With very low frequency (like 5-9 a day with 200 pods running), we are getting this error:

```log
java.lang.IndexOutOfBoundsException: index 1715
at java.util.concurrent.atomic.AtomicLongArray.checkedByteOffset(AtomicLongArray.java:65)
at java.util.concurrent.atomic.AtomicLongArray.getAndAdd(AtomicLongArray.java:215)
at java.util.concurrent.atomic.AtomicLongArray.incrementAndGet(AtomicLongArray.java:225)
at org.HdrHistogram.ConcurrentHistogram$AtomicLongArrayWithNormalizingOffset.atomicIncrement(ConcurrentHistogram.java:682)
at org.HdrHistogram.ConcurrentHistogram.recordConvertedDoubleValue(ConcurrentHistogram.java:170)
at org.HdrHistogram.DoubleHistogram.recordSingleValue(DoubleHistogram.java:367)
at org.HdrHistogram.DoubleHistogram.recordValue(DoubleHistogram.java:289)
```

HdrHistogram: 2.1.12
openjdk version "1.8.0_252"

**Comment by ygree** [comment]
According to the code it catches only: `ArrayIndexOutOfBoundsException`:

https://github.com/HdrHistogram/HdrHistogram/blob/e9e3d3ea7bfbc628863c7d20fd96489813690d84/src/main/java/org/HdrHistogram/DoubleHistogram.java#L358-L370

Whereas in our case it throws `IndexOutOfBoundsException` that depends on the Java version:

JDK 8

```java.lang.IndexOutOfBoundsException: index 10
at java.util.concurrent.atomic.AtomicLongArray.checkedByteOffset(AtomicLongArray.java:65)
at java.util.concurrent.atomic.AtomicLongArray.getAndAdd(AtomicLongArray.java:215)
at java.util.concurrent.atomic.AtomicLongArray.incrementAndGet(AtomicLongArray.java:225)
at org.HdrHistogram.ConcurrentHistogram$AtomicLongArrayWithNormalizingOffset.atomicIncrement(ConcurrentHistogram.java:682)
at org.HdrHistogram.AtomicLongArraySpec.$anonfun$new$2(HdrHistogramSpec.scala:12)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
at org.scalatest.Transformer.apply(Transformer.scala:22)
...
```

JDK 11

```
java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 10
at java.base/java.lang.invoke.VarHandle$1.apply(VarHandle.java:2011)
at java.base/java.lang.invoke.VarHandle$1.apply(VarHandle.java:2008)
at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:159)
at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:156)
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:62)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
at java.base/java.lang.invoke.VarHandleLongs$Array.getAndAdd(VarHandleLongs.java:721)
at java.base/java.lang.invoke.VarHandleGuards.guard_LIJ_J(VarHandleGuards.java:778)
at java.base/java.util.concurrent.atomic.AtomicLongArray.incrementAndGet(AtomicLongArray.java:234)
```
