### ISSUE TITLE
HistogramLogProcessor does not support IntCountsHistogram

### ISSUE THREAD

**Issue by kirtiteja** [HdrHistogram/HdrHistogram#63]
When i try to parse the log file with HistogramLogProcessor, I get the this error. I see in the code only DoubleHistogram and Histogram are supported by the LogProcessor. Is there a workaround to this? Is there any other way to read these histogram files?

Exception in thread "HistogramLogProcessor" java.lang.IllegalArgumentException: The buffer's encoded value byte size (4) does not match the Histogram's (8)
        at org.HdrHistogram.AbstractHistogram.decodeFromByteBuffer(AbstractHistogram.java:1778)
        at org.HdrHistogram.AbstractHistogram.decodeFromCompressedByteBuffer(AbstractHistogram.java:1886)
        at org.HdrHistogram.Histogram.decodeFromCompressedByteBuffer(Histogram.java:252)
        at org.HdrHistogram.EncodableHistogram.decodeFromCompressedByteBuffer(EncodableHistogram.java:55)
        at org.HdrHistogram.HistogramLogReader.nextIntervalHistogram(HistogramLogReader.java:232)
        at org.HdrHistogram.HistogramLogReader.nextIntervalHistogram(HistogramLogReader.java:136)
        at org.HdrHistogram.HistogramLogProcessor.run(HistogramLogProcessor.java:181)

**Comment by giltene** [comment]
I'm working on accepting any word size smaller than the target's in a coming code push. That would fix the above.

**Comment by kirtiteja** [comment]
Yes that should fix it. Thanks Gil.

**Comment by giltene** [comment]
Addressed with https://github.com/HdrHistogram/HdrHistogram/commit/24390be4d69caef61a522c415f16d67c3801aaa8 and included in 2.1.5
